name = "sa-master-worker"
main = "src/index.js"
compatibility_date = "2025-01-01"

[[d1_databases]]
binding = "DB"
database_name = "sa-master-db"
database_id = "ВСТАВТЕ_ВАШ_D1_ID"

[[r2_buckets]]
binding = "FILES"
bucket_name = "sa-master-files"

[vars]
ENVIRONMENT = "production"