name = "sa-master-worker"
main = "src/index.js"
compatibility_date = "2025-01-01"

[[d1_databases]]
binding = "DB"
database_name = "sa-master-db"
database_id = "61a1c743-519d-45ea-8d4f-1ac93df683ca"

[[r2_buckets]]
binding = "FILES"
bucket_name = "sa-master-files"

[vars]
ENVIRONMENT = "production"
CALCULATOR_URL = "https://sa-master.pro/calculator.html"
