export async function handleCreateRequest(request, env, headers) {
  // ...
  const tg = sendTelegram(env, telegramText);
  if (typeof globalThis.waitUntil === "function") globalThis.waitUntil(tg);
  // ...
}